CREATE TABLE IF NOT EXISTS `urls` (
  `id` INTEGER(255) NOT NULL AUTO_INCREMENT,
  `from` LONGTEXT NOT NULL,
  `to` LONGTEXT NOT NULL,
  `hash` LONGTEXT NOT NULL,

  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`)
);